FROM maven:3.6.3-jdk-11-slim AS builder

WORKDIR /root

COPY ./java-app/pom.xml /root
COPY ./java-app/src /root/src

RUN mvn clean package

FROM payara/server-full:5.2020.4-jdk11

COPY --from=builder /root/target/obamaphony-java-app-0.0.1-SNAPSHOT.war /opt/payara/deployments

EXPOSE 8080
EXPOSE 4848
