FROM maven:3.6.3-jdk-11-slim AS builder

WORKDIR /root

COPY ./java-app/pom.xml /root
COPY ./java-app/src /root/src

RUN mvn clean package

FROM tomcat:9

COPY --from=builder /root/target/obamaphony-java-app-0.0.1-SNAPSHOT.war \
    /usr/local/tomcat/webapps/ROOT.war

EXPOSE 8080
