FROM maven:3.6.3-jdk-11-slim AS builder

WORKDIR /root

COPY ./java-app/pom.xml /root
COPY ./java-app/src /root/src

RUN mvn clean package

FROM jboss/wildfly:20.0.1.Final

COPY --from=builder /root/target/obamaphony-java-app-0.0.1-SNAPSHOT.war /opt/jboss/wildfly/standalone/deployments/

RUN /opt/jboss/wildfly/bin/add-user.sh admin Admin#70365 --silent

CMD ["/opt/jboss/wildfly/bin/standalone.sh", "-b", "0.0.0.0", "-bmanagement", "0.0.0.0"]

EXPOSE 9990
EXPOSE 8080
